export enum LawEnum {
  SOCIETARIO = 'SOCIETARIO',
  LAVORO = 'LAVORO',
  COMMERCIALE = 'COMMERCIALE',
  CIVILE = 'CIVILE',
  IMMOBILIARE = 'IMMOBILIARE',
  CONTENZIOSO = 'CONTENZIOSO',
  TRIBUTARIO = 'TRIBUTARIO',
  PENALE = 'PENALE'
}

